name 'hoodpub'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures hoodpub'
long_description 'Installs/Configures hoodpub'
version '0.1.0'

depends 'hostsfile'
depends 'apt'
depends 'java'
